package saude.agenda.api.doctor;

public enum Specialty {
    OFTALMOLOGIA,
    ORTOPEDIA,
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    NEUROLOGIA,
    UROLOGIA,
    PSIQUIATRIA,
    OTORRINOLARINGOLOGIA,
    ANGIOLOGIA,
    GASTROENTEROLOGIA,
    PNEUMOLOGIA,
    NEFROLOGIA,
    GERIATRIA,
    HEMATOLOGIA,
    PROCTOLOGIA,
    MASTOLOGIA,
    HEPTOLOGIA,
    INFECTOLOGIA,
    ONCOLOGIA,
    TISIOLOGIA,
    OBSTETRICIA,
    GINECOLOGIA,
    PEDIATRIA

}
